kinde:
  oauth2:
    domain: ${KINDE_DOMAIN:https://your-domain.kinde.com}
    client-id: ${KINDE_CLIENT_ID:your-client-id-here}
    client-secret: ${KINDE_CLIENT_SECRET:your-client-secret-here}
    scopes: openid,email,profile,offline
    auto-config:
      enabled: true

