spring:
  security:
    oauth2:
      client:
        provider:
          kinde:
            issuer-uri: https://burntjam.kinde.com
        registration: 
          pkce: 
            provider: kinde
            client-id: d129efa11ffe436ca46e66aa16753e02
            client-secret: x9kxMgGeMuHD5rgs3xK4aulij5qnpqM6zRaRz4RsWwCt4Bu1e0a
            scope: openid,email
